org: kiplingcrossing
app: voting-app-api
service: voting-app-api

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-python-requirements
  - serverless-offline


provider:
  name: aws
  runtime: python3.7
  environment:
    MONGO_DB_USER: None
    MONGO_DB_PASS: None
    MONGO_DB_NAME: billsdb
    MONGO_DB_URL: localhost:27017
    MONGO_COLLECTION_NAME: billsserverless
  iamManagedPolicies:
    - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"

functions:
  create:
    handler: bill/create.create
    events:
      - http:
          path: bill
          method: post
          cors: true

  list:
    handler: bill/list.list
    events:
      - http:
          path: bill
          method: get
          cors: true

  get:
    handler: bill/get.get
    events:
      - http:
          path: bill/{id}
          method: get
          cors: true

  delete:
    handler: bill/delete.delete
    events:
      - http:
          path: bill/{id}
          method: delete
          cors: true
