org: kiplingcrossing
app: voting-app-api
service: voting-app-api

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-python-requirements
  - serverless-offline


provider:
  name: aws
  runtime: python3.7
  environment:
    MONGO_DB_USER: None
    MONGO_DB_PASS: None
    MONGO_DB_NAME: votingdb
    MONGO_DB_URL: localhost:27017
  iamManagedPolicies:
    - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"

functions:
  getbill:
    handler: bill/get.get
    events:
      - http:
          path: bill/{id}
          method: get
          cors: true

  listbill:
    handler: bill/list.list
    events:
      - http:
          path: bill
          method: get
          cors: true

  getissue:
    handler: issue/get.get
    events:
      - http:
          path: issue/{id}
          method: get
          cors: true

  listissue:
    handler: issue/list.list
    events:
      - http:
          path: issue
          method: get
          cors: true

  createuser:
    handler: user/create.create
    events:
      - http:
          path: user
          method: post
          cors: true

  listuser:
    handler: user/list.list
    events:
      - http:
          path: user
          method: get
          cors: true

  getuser:
    handler: user/get.get
    events:
      - http:
          path: user/{id}
          method: get
          cors: true

  deleteuser:
    handler: user/delete.delete
    events:
      - http:
          path: user/{id}
          method: delete
          cors: true
