app: voting-app-api
service: voting-app-api

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-python-requirements
  - serverless-offline


provider:
  name: aws
  runtime: python3.7
  environment:
    MONGO_DB_USER: None
    MONGO_DB_PASS: None
    MONGO_DB_NAME: votingdb
    MONGO_DB_URL: localhost:27017
  iamManagedPolicies:
    - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"

functions:
  getbill:
    handler: bill/get.get
    events:
      - http:
          path: bill/{id}
          method: get
          cors: true

  listbill:
    handler: bill/list.list
    events:
      - http:
          path: bill
          method: get
          cors: true

  getissue:
    handler: issue/get.get
    events:
      - http:
          path: issue/{id}
          method: get
          cors: true

  listissue:
    handler: issue/list.list
    events:
      - http:
          path: issue
          method: get
          cors: true

  getballot:
    handler: shitchain/get.get
    events:
      - http:
          path: shitchain/{id}
          method: get
          cors: true

  listballot:
    handler: shitchain/list.list
    events:
      - http:
          path: shitchain
          method: get
          cors: true

  makevote:
    handler: shitchain/create.create
    events:
      - http:
          path: shitchain
          method: post
          cors: true
          
  getresult:
    handler: result/get.get
    events:
      - http:
          path: result/{id}
          method: get
          cors: true

  listresult:
    handler: result/list.list
    events:
      - http:
          path: result
          method: get
          cors: true
